version: '3.8'
services:
  app:
    build:
      context: ./
    volumes:
      - ./cache.json:/app/cache.json:delegated
    command: npm run start
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: prod